// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20211111185935_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Review")
                        .HasColumnType("int");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Portland",
                            State = "OR",
                            Country = "U S A",
                            Review = 7
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Chicago",
                            State = "IL",
                            Country = "U S A",
                            Review = 7
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Las Vegas",
                            State = "Nevada",
                            Country = "U S A",
                            Review = 7
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Miyami",
                            State = "Florida",
                            Country = "U S A",
                            Review = 7
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "NewYork",
                            State = "NewYourk",
                            Country = "U S A",
                            Review = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
